version: '3.7'


services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    networks:
      - nest
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

networks:
  nest:
    external: true

volumes:
  postgres:
